name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ARCH="x86_64" make test
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
